// Tests de « Incrément possible » (Réglages > Exercices). Usage : node tools/tests/increment.js <dossier> [port]
const { chromium } = require('playwright');
const DIR = process.argv[2] || 'gymlog', PORT = process.argv[3] || '8815'; let ok = 0, ko = 0;
const check = (l, c, d) => { console.log(`${c ? '✓' : '✗'} ${l}${d !== undefined ? '  → ' + d : ''}`); c ? ok++ : ko++; };
(async () => { const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 414, height: 896 }, serviceWorkers: 'block' }); const p = await ctx.newPage(); await p.route('**/gstatic.com/**', (r) => r.abort());
  await p.addInitScript(() => { const noop = () => {}; const a = () => ({ onAuthStateChanged: noop, signOut: noop, setPersistence: () => Promise.resolve() }); a.Auth = { Persistence: { LOCAL: 'local' } }; window.firebase = { initializeApp: noop, auth: a, database: () => ({ ref: () => ({ once: () => Promise.resolve({ val: () => null }), set: () => Promise.resolve() }) }) }; });
  p.errs = []; p.on('pageerror', (e) => p.errs.push(e.message)); await p.goto(`http://localhost:${PORT}/${DIR}/index.html`, { waitUntil: 'load' }); await p.waitForFunction(() => { try { currentUser; return typeof render === 'function'; } catch (e) { return false; } });
  const reset = async (inc) => { await p.evaluate((inc) => { currentUser = { uid: 'u' }; gymExerciseConfigs = [{ id: 'c1', name: 'Squat', category: 'jambes', baseWeights: [40, 50, 60, 70], maxIncrement: inc, autoIncrement: false }]; gainageExerciseConfigs = []; sessions = []; gymSettingsFormOpen = false; currentApp = 'settings-gym'; render(); }, inc); await p.waitForTimeout(300); await p.click('[data-edit-config="c1"]'); await p.waitForTimeout(350); };
  const val = () => p.inputValue('#config-max-increment'); const hint = () => p.textContent('#config-increment-hint'); const saved = () => p.evaluate(() => gymExerciseConfigs.find((c) => c.id === 'c1').maxIncrement);
  const step = async (sel, n = 1) => { for (let i = 0; i < n; i++) { await p.click(sel); await p.waitForTimeout(160); } };
  console.log('=== Pas des boutons : 1 kg ===');
  await reset(1); check('Valeur existante de 1 kg : affichée telle quelle', (await val()) === '1');
  await step('#config-max-increment-plus', 2); check('+ puis + : 1 → 2 → 3', (await val()) === '3', await val());
  await step('#config-max-increment-minus', 2); check('− puis − : 3 → 2 → 1', (await val()) === '1', await val());
  await step('#config-max-increment-minus', 2); check('− au-delà de 0 : reste à 0 (jamais négatif)', (await val()) === '0', await val());
  await reset(0); await step('#config-max-increment-plus'); check('Nouvel exercice (0) : + donne 1', (await val()) === '1');
  await reset(2.5); check('Valeur existante de 2,5 kg : conservée, pas arrondie', (await val()) === '2.5');
  await step('#config-max-increment-plus'); check('2,5 + 1 = 3,5', (await val()) === '3.5', await val());
  console.log('\n=== Saisie directe (n\'importe quelle valeur) ===');
  await reset(0); await p.fill('#config-max-increment', ''); await p.type('#config-max-increment', '1.25'); check('Taper 1.25 : le texte d\'aide se met à jour en direct', /\+1\.25kg/.test(await hint()), await hint());
  await p.click('#save-config-btn'); await p.waitForTimeout(300); check('…et Enregistrer, sans autre geste entre les deux : 1.25 enregistré', (await saved()) === 1.25, String(await saved()));
  await p.click('[data-edit-config="c1"]'); await p.waitForTimeout(300); check('…rouvert : 1.25 relu', (await val()) === '1.25');
  await reset(0); await p.fill('#config-max-increment', ''); await p.type('#config-max-increment', '2,5'); check('Virgule française « 2,5 » : lue comme 2.5', (await val()) === '2.5', await val());
  await p.click('#save-config-btn'); await p.waitForTimeout(300); check('…enregistré : 2.5', (await saved()) === 2.5);
  await reset(3); await p.fill('#config-max-increment', 'abc'); await p.press('#config-max-increment', 'Tab'); await p.waitForTimeout(150); check('Texte illisible « abc » : retenu comme 0, et affiché 0', (await val()) === '0' && (await hint()).includes('+0kg'), await val());
  await reset(0); await p.fill('#config-max-increment', '0.5'); await p.press('#config-max-increment', 'Tab'); await step('#config-max-increment-plus'); check('0,5 saisi puis + : 1,5 (le pas s\'ajoute à la valeur saisie)', (await val()) === '1.5', await val());
  await p.click('#save-config-btn'); await p.waitForTimeout(300); check('…enregistré : 1.5', (await saved()) === 1.5);
  console.log('\n=== Effet réel dans l\'app ===');
  await reset(1); await p.click('#save-config-btn'); await p.waitForTimeout(300);
  await p.evaluate(() => { clearDraft(); draft.exercises = [{ id: 'e1', name: 'Squat', exType: 'muscu', category: 'jambes', sets: [{ id: 's1', weight: 60, reps: 10, weightMode: 'off' }] }]; saveJSON(KEYS.draft, draft); currentApp = 'gym'; tab = 'log'; gymTopMode = 'session'; renderGymApp(); }); await p.waitForTimeout(450);
  const lbl = await p.textContent('.increment-switch-btn'); await p.click('.increment-switch-btn'); await p.waitForTimeout(250); const w = await p.evaluate(() => serializeExercisesFromDOM().find((e) => e.name === 'Squat').sets[0].weight);
  check('Créer : l\'incrément de 1 kg donne 60 → 61', Number(w) === 61, `bouton « ${lbl.trim()} » puis poids ${w}`);
  await p.evaluate(() => { liveSession = null; currentApp = 'live'; render(); }); await p.waitForTimeout(300); await p.evaluate(() => document.querySelector('[data-live-category="jambes"]').click()); await p.waitForTimeout(300); await p.evaluate(() => document.querySelector('[data-live-exercise="Squat"]').click()); await p.waitForTimeout(450);
  await p.click('[data-live-toggle-increment]'); await p.waitForTimeout(250); check('Séance en direct : le bouton affiche « +1kg »', /\+1kg/.test(await p.textContent('[data-live-toggle-increment]')), (await p.textContent('[data-live-toggle-increment]')).trim());
  check('    aucune erreur JS', p.errs.length === 0, p.errs.join(' | ') || 'aucune');
  console.log(`\n${ok} réussis, ${ko} échoués`); await b.close(); process.exit(ko ? 1 : 0); })();
